import ytdl from '../lib/index.js';
export default ytdl;
export const getBasicInfo = ytdl.getBasicInfo;
export const getInfo = ytdl.getInfo;
export const chooseFormat = ytdl.chooseFormat;
export const filterFormats = ytdl.filterFormats;
export const validateURL = ytdl.validateURL;
export const validateID = ytdl.validateID;
export const getURLVideoID = ytdl.getURLVideoID;
export const getVideoID = ytdl.getVideoID;
export const createAgent = ytdl.createAgent;
export const createProxyAgent = ytdl.createProxyAgent;
export const downloadFromInfo = ytdl.downloadFromInfo;
export const downloadFromQuery = ytdl.downloadFromQuery;
export const search = ytdl.search;
export const searchOne = ytdl.searchOne;
export const errors = ytdl.errors;
export const cache = ytdl.cache;
